# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/dispenser.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/dispenser.proto\"\x8c\x01\n\x12RequestUnitMessage\x12\x11\n\tfull_name\x18\x01 \x01(\t\x12\x15\n\rphone_numbers\x18\x02 \x03(\t\x12\x0e\n\x06\x65mails\x18\x03 \x03(\t\x12\x11\n\taddresses\x18\x04 \x03(\t\x12\x17\n\x0fpassport_number\x18\x05 \x01(\t\x12\x10\n\x08\x62irthday\x18\x06 \x01(\t\"5\n\x0bValidString\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x17\n\x0frequested_value\x18\x02 \x01(\t\"\xde\x01\n\x10ValidUnitMessage\x12\x1f\n\tfull_name\x18\x01 \x01(\x0b\x32\x0c.ValidString\x12#\n\rphone_numbers\x18\x02 \x03(\x0b\x32\x0c.ValidString\x12\x1c\n\x06\x65mails\x18\x03 \x03(\x0b\x32\x0c.ValidString\x12\x1f\n\taddresses\x18\x04 \x03(\x0b\x32\x0c.ValidString\x12%\n\x0fpassport_number\x18\x05 \x01(\x0b\x32\x0c.ValidString\x12\x1e\n\x08\x62irthday\x18\x06 \x01(\x0b\x32\x0c.ValidString\"C\n\x13ResponseUnitMessage\x12\x0c\n\x04guid\x18\x01 \x01(\r\x12\x1e\n\x03msg\x18\x02 \x01(\x0b\x32\x11.ValidUnitMessage2N\n\x13ValidationDispenser\x12\x37\n\x08Validate\x12\x13.RequestUnitMessage\x1a\x14.ResponseUnitMessage\"\x00\x62\x06proto3')



_REQUESTUNITMESSAGE = DESCRIPTOR.message_types_by_name['RequestUnitMessage']
_VALIDSTRING = DESCRIPTOR.message_types_by_name['ValidString']
_VALIDUNITMESSAGE = DESCRIPTOR.message_types_by_name['ValidUnitMessage']
_RESPONSEUNITMESSAGE = DESCRIPTOR.message_types_by_name['ResponseUnitMessage']
RequestUnitMessage = _reflection.GeneratedProtocolMessageType('RequestUnitMessage', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTUNITMESSAGE,
  '__module__' : 'proto.dispenser_pb2'
  # @@protoc_insertion_point(class_scope:RequestUnitMessage)
  })
_sym_db.RegisterMessage(RequestUnitMessage)

ValidString = _reflection.GeneratedProtocolMessageType('ValidString', (_message.Message,), {
  'DESCRIPTOR' : _VALIDSTRING,
  '__module__' : 'proto.dispenser_pb2'
  # @@protoc_insertion_point(class_scope:ValidString)
  })
_sym_db.RegisterMessage(ValidString)

ValidUnitMessage = _reflection.GeneratedProtocolMessageType('ValidUnitMessage', (_message.Message,), {
  'DESCRIPTOR' : _VALIDUNITMESSAGE,
  '__module__' : 'proto.dispenser_pb2'
  # @@protoc_insertion_point(class_scope:ValidUnitMessage)
  })
_sym_db.RegisterMessage(ValidUnitMessage)

ResponseUnitMessage = _reflection.GeneratedProtocolMessageType('ResponseUnitMessage', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEUNITMESSAGE,
  '__module__' : 'proto.dispenser_pb2'
  # @@protoc_insertion_point(class_scope:ResponseUnitMessage)
  })
_sym_db.RegisterMessage(ResponseUnitMessage)

_VALIDATIONDISPENSER = DESCRIPTOR.services_by_name['ValidationDispenser']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTUNITMESSAGE._serialized_start=26
  _REQUESTUNITMESSAGE._serialized_end=166
  _VALIDSTRING._serialized_start=168
  _VALIDSTRING._serialized_end=221
  _VALIDUNITMESSAGE._serialized_start=224
  _VALIDUNITMESSAGE._serialized_end=446
  _RESPONSEUNITMESSAGE._serialized_start=448
  _RESPONSEUNITMESSAGE._serialized_end=515
  _VALIDATIONDISPENSER._serialized_start=517
  _VALIDATIONDISPENSER._serialized_end=595
# @@protoc_insertion_point(module_scope)
